on: push
name: on push
jobs:
  Tests:
    name: base
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', 'pypy3.9', 'pypy3.10']
        # os: ['ubuntu-latest', 'windows-latest', 'macOs-latest']
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true
    - name: prepare
      run: pip install -U setuptools wheel
    - name: install
      run: pip install .[dev,ci]
    - name: test
      run: python -m pytest --reruns 5 tests/ --cov oscpy/ --cov-branch
    - name: coveralls
      run: python -m coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
